<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Accounts\EventHandlers\**" />
    <Compile Remove="Features\Roles\EventHandlers\**" />
    <EmbeddedResource Remove="Features\Accounts\EventHandlers\**" />
    <EmbeddedResource Remove="Features\Roles\EventHandlers\**" />
    <None Remove="Features\Accounts\EventHandlers\**" />
    <None Remove="Features\Roles\EventHandlers\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\IdentityService.Domain\IdentityService.Domain.csproj" />
  </ItemGroup>

</Project>
